CREATE  PROCEDURE refresh_disclosure_mv(
)
BEGIN

	TRUNCATE TABLE DISCLOSURE_MV;

	INSERT INTO DISCLOSURE_MV
	(
	DOCUMENT_NUMBER,
	COI_DISCLOSURE_ID,
	COI_DISCLOSURE_NUMBER,
	SEQUENCE_NUMBER,
	PERSON_ID,
	FULL_NAME,
	DISCLOSURE_DISPOSITION_CODE,
	DISCLOSURE_DISPOSITION,
	DISCLOSURE_STATUS_CODE,
	DISCLOSURE_STATUS,
	MODULE_ITEM_KEY,
	DISC_ACTIVE_STATUS,
	EXPIRATION_DATE,
	UPDATE_TIMESTAMP,
	UPDATE_USER
	)

	SELECT         
		T1.DOCUMENT_NUMBER,
		T1.COI_DISCLOSURE_ID,
		T1.COI_DISCLOSURE_NUMBER,
		T1.SEQUENCE_NUMBER,
		T1.PERSON_ID,
		(T5.LAST_NM||', '||T5.FIRST_NM||' '||T5.MIDDLE_NM)   AS FULL_NAME,
		T1.DISCLOSURE_DISPOSITION_CODE,
		T3.DESCRIPTION AS DISCLOSURE_DISPOSITION,
		T1.DISCLOSURE_STATUS_CODE,
		T2.DESCRIPTION AS DISCLOSURE_STATUS,
		T1.MODULE_ITEM_KEY,
		T1.DISC_ACTIVE_STATUS,
		T1.EXPIRATION_DATE,
		T1.UPDATE_TIMESTAMP,
		T1.UPDATE_USER 
	FROM COI_DISCLOSURE T1 
	INNER JOIN COI_DISCLOSURE_STATUS T2 ON T2.COI_DISCLOSURE_STATUS_CODE = T1.DISCLOSURE_STATUS_CODE 
	INNER JOIN COI_DISPOSITION_STATUS T3 ON T3.COI_DISPOSITION_CODE = T1.DISCLOSURE_DISPOSITION_CODE
	LEFT OUTER JOIN KRIM_PRNCPL_T T4 ON T4.PRNCPL_ID = T1.PERSON_ID 
	LEFT OUTER JOIN KRIM_ENTITY_NM_T T5 ON T4.ENTITY_ID = T5.ENTITY_ID;
    COMMIT;
END