CREATE TABLE AWARD_MV
(
DOCUMENT_NUMBER VARCHAR(40),
AWARD_NUMBER	VARCHAR(12),
AWARD_ID		decimal(22,0),
TITLE			VARCHAR(200),
ACCOUNT_NUMBER	VARCHAR(7),
SEQUENCE_NUMBER	decimal(4,0),
STATUS 			VARCHAR(200),
SPONSOR 		VARCHAR(200),
SPONSOR_CODE 	VARCHAR(6),
UNIT_NUMBER 	VARCHAR(8),
UNIT_NAME 		VARCHAR(60),
full_name 		VARCHAR(255),
PERSON_ID		VARCHAR(40),
UPDATE_TIMESTAMP datetime,
UPDATE_USER		VARCHAR(60)
);
CREATE TABLE DISCLOSURE_MV
(
DOCUMENT_NUMBER				VARCHAR(40),
COI_DISCLOSURE_ID			DECIMAL(12,0),
COI_DISCLOSURE_NUMBER		VARCHAR(20),
SEQUENCE_NUMBER				DECIMAL(6,0),
PERSON_ID					VARCHAR(40),
FULL_NAME					VARCHAR(163),
DISCLOSURE_DISPOSITION_CODE	DECIMAL(3,0),
DISCLOSURE_DISPOSITION		VARCHAR(200),
DISCLOSURE_STATUS_CODE		DECIMAL(3,0),
DISCLOSURE_STATUS			VARCHAR(200),
MODULE_ITEM_KEY				VARCHAR(20),
DISC_ACTIVE_STATUS			DECIMAL(1,0),
EXPIRATION_DATE				DATE,
UPDATE_TIMESTAMP			DATE,
UPDATE_USER					VARCHAR(60)
);
CREATE TABLE IACUC_MV
(
PROTOCOL_ID			DECIMAL(12,0),
DOCUMENT_NUMBER		VARCHAR(40),
PROTOCOL_NUMBER		VARCHAR(20),
SEQUENCE_NUMBER		DECIMAL(4,0),
VER_NBR				DECIMAL(8,0),
TITLE				VARCHAR(2000),
LEAD_UNIT_NUMBER	VARCHAR(8),
LEAD_UNIT			VARCHAR(60),
PROTOCOL_TYPE_CODE	VARCHAR(3),
PROTOCOL_TYPE		VARCHAR(200),
STATUS_CODE			VARCHAR(3),
STATUS				VARCHAR(200),
EXPIRATION_DATE		DATE,
UPDATE_TIMESTAMP	DATE,
UPDATE_USER			VARCHAR(60),
PERSON_ID			VARCHAR(40),
FULL_NAME			VARCHAR(90)
);
CREATE TABLE IRB_MV
(
PROTOCOL_ID			DECIMAL(12,0),
DOCUMENT_NUMBER		VARCHAR(40),
PROTOCOL_NUMBER		VARCHAR(20),
SEQUENCE_NUMBER		DECIMAL(4,0),
VER_NBR				DECIMAL(8,0),
TITLE				VARCHAR(2000),
LEAD_UNIT_NUMBER	VARCHAR(8),
LEAD_UNIT			VARCHAR(60),
PROTOCOL_TYPE_CODE	VARCHAR(3),
PROTOCOL_TYPE		VARCHAR(200),
STATUS_CODE			VARCHAR(3),
STATUS				VARCHAR(200),
EXPIRATION_DATE		DATE,
UPDATE_TIMESTAMP	DATE,
UPDATE_USER			VARCHAR(60),
PERSON_ID			VARCHAR(40),
FULL_NAME			VARCHAR(90)
);
create table KC_PERSON_MV
(
PRNCPL_ID               varchar(40),  
PRNCPL_NM              varchar(100), 
FIRST_NM               varchar(40),  
MIDDLE_NM              varchar(40),  
LAST_NM                varchar(80),  
FULL_NAME              varchar(163), 
EMAIL_ADDR             varchar(200), 
PRMRY_DEPT_CD          varchar(40),  
UNIT_NAME              varchar(60),  
UNIT_NUMBER            varchar(8),   
PHONE_NBR              varchar(20),  
ADDR_LINE_1            varchar(128)
);
CREATE TABLE PROPOSALS_MV
(
DOCUMENT_NUMBER			VARCHAR(40),
PROPOSAL_NUMBER			VARCHAR(12),
VER_NBR					DECIMAL(8,0),
TITLE					VARCHAR(200),
LEAD_UNIT_NUMBER 		VARCHAR(8),
LEAD_UNIT 				VARCHAR(60),
SPONSOR_CODE 			CHAR(6),
SPONSOR 				VARCHAR(200),
DEADLINE_DATE 			DATE,
STATUS_CODE 			DECIMAL(3,0),
STATUS 					VARCHAR(200),
UPDATE_TIMESTAMP 		DATE,
UPDATE_USER 			VARCHAR(60),
PERSON_ID 				VARCHAR(40),
FULL_NAME 			  	VARCHAR(90),
CERTIFIED 			  	CHAR(1),
PROP_PERSON_ROLE_CODE 	VARCHAR(12)
);
CREATE TABLE MITKC_UNIT_WITH_CHILDREN(
UNIT_NUMBER VARCHAR(8),
UNIT_NAME VARCHAR(60),
CHILD_UNIT_NUMBER VARCHAR(8),
CHILD_UNIT_NAME VARCHAR(60) 
);
create table MITKC_USER_RIGHT_MV
(
PERSON_ID          VARCHAR(40),  
UNIT_NUMBER        VARCHAR(400), 
DESCEND_FLAG       VARCHAR(400), 
PERM_NM            VARCHAR(100),
ACTV_TO_DT		   DATETIME
);
create table unit_tmp
(
id  				int,
UNIT_NUMBER 		varchar(8),
UNIT_NAME			varchar(60),
PARENT_UNIT_NUMBER	varchar(8),
parent_id 			int,
ACTIVE_FLAG		char(1)
);
